#Ejercicio 1
##Leslie Janeth Quincosa Ramírez
Métodos numéricos, ayudantía
12 de agosto de 2023

In [37]:
import numpy as np

Función que soluciona un sistema de ecuaciones de $n \times n$ con una matriz diagonal

In [38]:
def diagonalMatrix(A, b):
  det = 1
  n = A.shape[0]
  x = np.zeros(n)

  for i in range (n):
    det *= A[i][i]

    if det == 0:
      print("A no es invertible")
      return

    x[i] = b[i]/(A[i][i])
  return x

Pruebas matriz diagonal

Ejemplos de matrices de $3 \times 3$ diagonales, una invertible y otra no invertible.

In [39]:
A = np.array([[2, 0, 0], [0, 3, 0], [0, 0, -2]])
b = np.array([10, 15, 2])

In [40]:
diagonalMatrix(A, b)

array([ 5.,  5., -1.])

In [41]:
A_det = np.array([[0, 0, 0], [0, 3, 0], [0, 0, -2]])
b = np.array([10, 15, 2])

In [42]:
diagonalMatrix(A_det, b)

A no es invertible


Función que soluciona un sistema de ecuaciones de $n \times n$ con una matriz triangular inferior

In [43]:
def TriangularInf(A, b):
  det = 1
  n = A.shape[0]
  x = np.zeros(n)

  for i in range (n):
    det *= A[i][i]

    if det == 0:
      print("A no es invertible")
      return

    sum = 0
    for j in range(i):
      sum += x[j]*(A[i][j])

    x[i] = (b[i]- sum)/A[i][i]
  return x

Pruebas matriz inferior
Ejemplos de matrices de $3 \times 3$ diagonales, usando el mismo ejemplo de la matriz diagonal anterior y de otra matriz diagonal inferior.

In [44]:
TriangularInf(A, b)

array([ 5.,  5., -1.])

In [45]:
A_inf = np.array([[2, 0, 0], [-1, 3, 0], [3, 5, -2]])

In [46]:
TriangularInf(A_inf, b)

array([ 5.        ,  6.66666667, 23.16666667])

Función que soluciona un sistema de ecuaciones de $n \times n$ con una matriz triangular superior



In [47]:
def TriangularSup(A, b):
  det = 1
  n = A.shape[0]
  x = np.zeros(n)

  for i in reversed(range(n)): #Es la misma función que TriangularInf solo que empezamos de n a 0
    det *= A[i][i]

    if det == 0:
      print("A no es invertible")
      return

    sum = 0
    for j in range(i, n):
      sum += x[j]*(A[i][j])

    x[i] = (b[i]- sum)/A[i][i]
  return x

Pruebas matriz superior
Ejemplos de matrices de $3 \times 3$ diagonales, éste algoritmo es una modificación del anterior, comenzando de abajo hacia arriba.

In [48]:
TriangularSup(A, b)

array([ 5.,  5., -1.])

In [49]:
A_sup = np.array([[6, 10, -2], [0, 4, -1],[0, 0, 2] ])

In [50]:
TriangularSup(A_sup, b)

array([-4.66666667,  4.        ,  1.        ])

In [51]:
A_sup5 = np.array([[6, 10, -2, 10, 1], [0, 4, -1, 15, 1],[0, 0, 2, 2, 1], [0, 0, 0, 1, 1], [0, 0, 0, 0, 1]])
b5 = np.array([1, 2, 3, 4, 5])

In [52]:
TriangularSup(A_sup5, b5)

array([-4.,  3.,  0., -1.,  5.])